### ISSUE TITLE
What is the rational for the new execute_pat_year_queries query?

### ISSUE THREAD

**Issue by tobiasgirardet** [medizininformatik-initiative/mii-fhir-site-report-aktin#39]
Recently, the [execute_pat_year_queries](https://github.com/medizininformatik-initiative/mii-fhir-site-report-aktin/blob/685fd90d278a90c211098b274c194c0412630ae9/site-client/aktin-fhir-mii-report-client.py#L224) query was added to the script. In contrast to the other queries, this query does not only retrieve a count summary, but instead, it pages through all encounters of a specific year and determines the number of unique patient IDs that have been referenced by the encounters of each year.

This makes the whole script execution much slower and is a little bit cumbersome if the number of encounters is in the 8 digit range. In addition, the query does not differentiate between the different types of encounters (e.g. Einrichtungskontakt, Abteilungskontakt, ...), so I am not quite sure why this information is useful. Can you explain the rational for this query?

**Comment by alexzautke** [comment]
Hallo @tobiasgirardet, die abgefragten Daten fließen aggregiert in das öffentlichen Schaufenster unter https://forschen-fuer-gesundheit.de (siehe "Datenübersicht"). Das hier keine Differenzierung nach Encounter.type erfolgt ist ein Fehler meiner Ansicht nach (@juliangruendner Wir sollten das gemeinsam nochmal besprechen).

Wäre es hilfreicher, wenn die Abfragen für das öffentliche Schaufenster unabhängig ausgeführt würden von den Abfragen der internen Kennzahlen?

**Comment by tobiasgirardet** [comment]
Hi! Verstehe ich leider noch nicht ganz. Wo in der Datenübersicht werden die Daten aus der [execute_pat_year_queries](https://github.com/medizininformatik-initiative/mii-fhir-site-report-aktin/blob/685fd90d278a90c211098b274c194c0412630ae9/site-client/aktin-fhir-mii-report-client.py#L224) Query denn aggregiert angezeigt? Sind das die "Personen"? Dann würden ja Patienten mehrfach gezählt, wenn sie in verschiedenen Jahren in Behandlung waren.

Sorry, steht hier vielleicht gerade aber auch auf dem Schlauch...

**Comment by alexzautke** [comment]
Ah sorry, hätte ich klarstellen müssen. Ja genau, Patienten mit mehrfachen Fällen werden doppelt gezählt. Für eine erste Version der öffentlichen Kennzahlen wurde dies erstmal so hingenommen.

**Comment by tobiasgirardet** [comment]
Ok. Danke für die Klarstellung.

Zur anderen Frage: Nein, es macht für uns eigentlich keinen Unterschied, ob die Anfragen für das öffentliche Schaufenster seperat ausgeführt werden oder nicht. 

Wir werden schauen, ob wir die Performance unserer Systeme optimieren können, um das Problem zu lösen.

Danke!
