### ISSUE TITLE
Profile URL of MII consent resources has changed

### ISSUE THREAD

**Issue by RaffaelBild** [medizininformatik-initiative/mii-fhir-site-report-aktin#42]
In the recent stable version of the MII consent module, the profile URL to use for consent resources has changed to
https://www.medizininformatik-initiative.de/fhir/modul-consent/StructureDefinition/mii-pr-consent-einwilligung
(see the [profile definition on simplifier.net](https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.consent/1.0.2/files/1938502))
It would be great if the queries issued by the site-client could be updated accordingly so that they (also) identify consent resources with this new profile URL correctly as MII consent resources.

**Comment by juliangruendner** [comment]
@RaffaelBild  - part of this pull request https://github.com/medizininformatik-initiative/mii-fhir-site-report-aktin/pull/41

**Comment by RaffaelBild** [comment]
@juliangruendner excellent, thanks
